<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="2" time="0.147"><testcase classname="test_sample" file="test_sample.py" line="4" name="test_answer1" time="0.0009791851043701172"></testcase><testcase classname="test_sample" file="test_sample.py" line="11" name="test_answer2" time="0.0035011768341064453"><failure message="assert 5 == 6
 +  where 5 = func(4)">def test_answer2():
&gt;       assert func(4) == 6
E       assert 5 == 6
E        +  where 5 = func(4)

test_sample.py:13: AssertionError</failure></testcase></testsuite>